name: Deploy-Drim UI

on: push

jobs:
  deploy-uxpin:
    name: UXpin update
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@main
        with:
          ref: refs/heads/main
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn
      - name: Push To UXpin
        run: yarn push
        env:
          UXPIN_AUTH_TOKEN: ${{ secrets.6f3cad99cc022c0df049cff125d5c0104df89f2a }}
